# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/restaurants', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Restaurant. As you add validations to Restaurant, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      "name": 'Burj',
      "email": 'burj@gmail.com',
      "cuisines": 'veg',
      "phone": '1233343434',
      "location": 'dubai',
      "open_hours": 'Mon-Fri'
    }
  end

  let(:invalid_attributes) do
    {
      "name": '',
      "email": 's@gl.com',
      "cuisines": 'veg',
      "phone": '1233343434',
      "location": 'dubai',
      "open_hours": 'Mon-Fri'
    }
  end

  let(:user_restaurant) do
    Restaurant.create!(name: 'Burj', cuisines: 'veg', phone: '242342342', email: 'burj@gmail.com', location: 'Dubai',
                       open_hours: 'Mon-Fri')
  end

  let(:user) do
    User.create!(first_name: 'Ashwini', last_name: 'Sukale', email: 'ashwini@gmail.com', phone: '1234322423',
                 role: 'admin', restaurant_id: user_restaurant.id, password: '123456', password_confirmation: '123456')
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # RestaurantsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    token = JsonWebToken.encode(user_id: user.id)
    { 'Authorization': token, 'Content-Type': 'application/json' }
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Restaurant.create! valid_attributes
      get api_v1_restaurants_path, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      restaurant = Restaurant.create! valid_attributes
      get api_v1_restaurant_path(id: restaurant.id), headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Restaurant' do
        expect do
          post api_v1_restaurants_path,
               params: { restaurant: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Restaurant, :count).by(2) # Because we have already created one restaurant in let block, it will change by 2 not by 1
      end

      it 'renders a JSON response with the new restaurant' do
        post api_v1_restaurants_path,
             params: { restaurant: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Restaurant' do
        expect do
          post api_v1_restaurants_path,
               params: { restaurant: invalid_attributes }, as: :json
        end.to change(Restaurant, :count).by(0)
      end

      it 'renders a JSON response with errors for the new restaurant' do
        post api_v1_restaurants_path,
             params: { restaurant: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match('application/json')
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          "name": 'Khalifa',
          "email": 'burj@gmail.com',
          "cuisines": 'veg',
          "phone": '1233343434',
          "location": 'dubai',
          "open_hours": 'Mon-Fri'
        }
      end

      it 'updates the requested restaurant' do
        restaurant = Restaurant.create! valid_attributes
        patch api_v1_restaurant_path(id: restaurant.id),
              params: { restaurant: new_attributes }, headers: valid_headers, as: :json
        restaurant.reload
        expect(restaurant.name).to eq('Khalifa')
      end

      it 'renders a JSON response with the restaurant' do
        restaurant = Restaurant.create! valid_attributes
        patch api_v1_restaurant_path(id: restaurant.id),
              params: { restaurant: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the restaurant' do
        restaurant = Restaurant.create! valid_attributes
        patch api_v1_restaurant_path(id: restaurant.id),
              params: { restaurant: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match('application/json')
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested restaurant' do
      restaurant = Restaurant.create! valid_attributes
      expect do
        delete api_v1_restaurant_path(id: restaurant.id), headers: valid_headers, as: :json
      end.to change(Restaurant, :count).by(0) # Because we have already created one restaurant in let block, it will change by 0 not by -1
    end
  end

  describe '#with Admin role' do
    it "should create restaurant" do
      expect do
        post api_v1_restaurants_path,
             params: { restaurant: valid_attributes }, headers: valid_headers, as: :json
      end.to change(Restaurant, :count).by(2)
    end
  end

  describe '#with Non Admin role' do
    it "should not create restaurant" do
      guest = User.create!(first_name: 'Ashwini', last_name: 'Sukale', email: 'ashwini@gmail.com', phone: '1234322423',
                   role: 'guest', restaurant_id: user_restaurant.id, password: '123456', password_confirmation: '123456')
      token = JsonWebToken.encode(user_id: guest.id)
      valid_headers = { 'Authorization': token, 'Content-Type': 'application/json' }
      expect do
        post api_v1_restaurants_path,
             params: { restaurant: valid_attributes }, headers: valid_headers, as: :json
      end.to change(Restaurant, :count).by(0)
    end
  end
end
